### ISSUE TITLE
Career Match Call seems to be failing for fr-fr locale.

### ISSUE THREAD

**Issue by amitDocs** [traitify/traitify-widgets#124]
**Request URL:** `https://api-sandbox.traitify.com/v1/assessments/1cda5e29-443a-411b-9d06-71b1b57163e2/matches/careers?careers_per_page=100&locale_key=fr-fr&paged=true`

**Response:** `[{"id":"20a8e244-7c34-4266-af20-f1420133f8f1-1","error_type":"GENERAL_ERROR","message":"NullPointerException: ","error_code":"NOT_FOUND","name":null,"value":null}]`

Here below is the code which i'm using to make above career match call.

```
<head>
<script src="https://cdn.traitify.com/js/v2/traitify.js"></script>
<script>
var traitifyHostApi = '${traitifyHostApi}'; 
var traitifyPublicKey = '${traitifyPublicKey}';
var assessmentId = '${assessmentId}';
Traitify.setHost(traitifyHostApi);
Traitify.setPublicKey(traitifyPublicKey);
Traitify.setVersion("v1");
var widgets = Traitify.ui.component({careerOptions:{perPage:100}});
	widgets.assessmentId(assessmentId);
	widgets.locale("fr-fr");
	widgets.targets({
		CareerResults: ".splt-careers" 
       });
       widgets.render();
</script>
</head>
<body>
     <div class="splt-careers"></div>
</body>
```

Please let me know if career match api supports internationalization or not. 

I tried another approach to fetch career match with career.js widget like shown below but seems like this career.js widget doesn't support internationalization as i didn't find any option to set the locale. Please let me know if there is any way to achieve internationalization through career.js widget
```
<head>
<script src="https://cdn.traitify.com/js/v2/traitify.js"></script>
<script src="https://cdn.traitify.com/js/widgets/v1.js"></script>
<script src="https://cdn.traitify.com/js/widgets/careers.js"></script>
<script>
var traitifyHostApi = '${traitifyHostApi}'; 
var traitifyPublicKey = '${traitifyPublicKey}';
var assessmentId = '${assessmentId}';
Traitify.setHost(traitifyHostApi);
Traitify.setPublicKey(traitifyPublicKey);
Traitify.setVersion("v1");
var traitify = Traitify.ui.load("careers", assessmentId, ".splt-careers", {
		careers : {
			number_of_matches : 100,
			columns : 5
		}
});
</script>
</head>
<body>
     <div class="splt-careers"></div>
</body>
```

**Comment by efleming** [comment]
@amitDocs We don't currently support `fr-fr` for career matches. We have it in our plans to add those translations, but we don't have an estimate on when they will be added. We do support `fr-us` and fr-ca` if you'd like to use one of those until we're able to add the new translations for `fr-fr`.
